
import java.awt.CardLayout;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Mahasiswa
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        btnApel = new javax.swing.JButton();
        btnDurian = new javax.swing.JButton();
        btnMangga = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        imagePanel = new javax.swing.JPanel();
        labelApel = new javax.swing.JLabel();
        labelDurian = new javax.swing.JLabel();
        labelMangga = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        btnApel.setText("Apel");
        btnApel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApelActionPerformed(evt);
            }
        });
        buttonPanel.add(btnApel);

        btnDurian.setText("Durian");
        btnDurian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDurianActionPerformed(evt);
            }
        });
        buttonPanel.add(btnDurian);

        btnMangga.setText("Mangga");
        btnMangga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManggaActionPerformed(evt);
            }
        });
        buttonPanel.add(btnMangga);

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        buttonPanel.add(btnKeluar);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_START);

        imagePanel.setLayout(new java.awt.CardLayout());

        labelApel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelApel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apel.jpg"))); // NOI18N
        imagePanel.add(labelApel, "0");

        labelDurian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDurian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/durian.jpg"))); // NOI18N
        imagePanel.add(labelDurian, "1");

        labelMangga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMangga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mangga.jpg"))); // NOI18N
        imagePanel.add(labelMangga, "2");

        getContentPane().add(imagePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnApelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApelActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(imagePanel.getLayout());
        cl.show(imagePanel, "0");
    }//GEN-LAST:event_btnApelActionPerformed

    private void btnDurianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDurianActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(imagePanel.getLayout());
        cl.show(imagePanel, "1");
    }//GEN-LAST:event_btnDurianActionPerformed

    private void btnManggaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManggaActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(imagePanel.getLayout());
        cl.show(imagePanel, "2");        
    }//GEN-LAST:event_btnManggaActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
                NewJFrame fullFrame = new NewJFrame();
                GraphicsDevice device = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
                device.setFullScreenWindow(fullFrame);
                fullFrame.setVisible(true);                        
                
                        
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApel;
    private javax.swing.JButton btnDurian;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnMangga;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JLabel labelApel;
    private javax.swing.JLabel labelDurian;
    private javax.swing.JLabel labelMangga;
    // End of variables declaration//GEN-END:variables
}
